"""Services / files."""

from __future__ import annotations

from PIL import Image
from app.config import settings
from app.core.oss import StorageConfigurationError
from app.core.oss import asset_url as _oss_asset_url
from app.core.oss import is_oss_ref
from app.core.oss import oss_ref
from app.core.storage import copy_into
from app.core.oss import storage as oss_storage
from fastapi import HTTPException
from fastapi import UploadFile
from pathlib import Path
from urllib.parse import quote
from contextlib import contextmanager
from contextvars import ContextVar
import logging
import io
import os
import uuid

logger = logging.getLogger(__name__)

# Keep Pillow decompression-bomb protection enabled for image processing.
Image.MAX_IMAGE_PIXELS = 50_000_000


PPT_EXTENSIONS = {".pptx"}


OFFICE_EXTENSIONS = {".ppt", ".pptx", ".pot", ".potx", ".pps", ".ppsx"}


def _validate_office_upload(upload: UploadFile) -> None:
    suffix = Path(upload.filename or "").suffix.lower()
    if suffix not in OFFICE_EXTENSIONS:
        raise HTTPException(400, "请上传 PPT/PPTX/POT/POTX/PPS/PPSX Office 文件")


def _validate_png_upload(upload: UploadFile) -> None:
    suffix = Path(upload.filename or "").suffix.lower()
    if suffix != ".png":
        raise HTTPException(400, "请上传 PNG 文件")


def _compress_hd_image(source_path: Path) -> Path:
    """Normalize an input image to the one persisted HD PNG asset.

    Card-sized variants are generated by OSS image processing at read time;
    the local staging file is therefore always converted to PNG before upload.
    """
    with Image.open(source_path) as img:
        w, h = img.size
        max_res = settings.image_hd_max_resolution
        needs_resize = max(w, h) > max_res
        if source_path.suffix.lower() == ".png" and not needs_resize:
            return source_path
        if needs_resize:
            img.thumbnail((max_res, max_res), Image.Resampling.LANCZOS)
        dpi = settings.image_hd_dpi
        new_path = source_path.with_suffix(".png")
        temp_path = new_path.with_name(f".{new_path.name}.{uuid.uuid4().hex}.tmp")
        # PNG preserves alpha and is the canonical persisted preview format.
        img.save(temp_path, format="PNG", dpi=(dpi, dpi))
        os.replace(temp_path, new_path)
        if new_path != source_path:
            source_path.unlink(missing_ok=True)
        return new_path


_ALLOWED_FILE_DIRS: list[Path] = []
_MATERIALIZED_REFS: dict[Path, str] = {}
_MATERIALIZED_SCOPE: ContextVar[set[Path] | None] = ContextVar("slide_flow_materialized_scope", default=None)


def persist_asset(source_path: Path, category: str) -> str:
    """Upload a validated working file and return the database asset reference."""
    backend = getattr(settings, "storage_backend", "local").strip().lower()
    if backend == "oss":
        ref = oss_storage.upload_file(source_path, oss_storage.key(category, source_path.suffix.lower()))
        return ref
    if backend != "local":
        raise StorageConfigurationError("storage.backend 只能配置为 local 或 oss")
    # Keep the local backend usable for development/tests: callers generally
    # pass a TemporaryDirectory path, so copy it into the durable local root.
    if category.startswith("templates/"):
        destination = settings.templates_dir
    elif category.startswith("resources/"):
        destination = settings.resources_dir
    elif category.startswith("avatars/"):
        destination = settings.assets_dir / "avatars"
    else:
        destination = settings.assets_dir
    return settings.store_path(copy_into(source_path, destination, "asset_"))


def persist_asset_copy(source_ref: str | None, category: str) -> str | None:
    if not source_ref:
        return None
    if not is_oss_ref(source_ref):
        source = settings.abs_path(source_ref)
        return persist_asset(source, category) if source and source.exists() else None
    source = oss_storage.materialize(source_ref)
    try:
        return persist_asset(source, category)
    finally:
        source.unlink(missing_ok=True)


def asset_preview_url(ref: str | None, *, thumb: bool = False) -> str | None:
    """Return a direct OSS URL; OSS image processing creates card thumbnails."""
    if not ref or not is_oss_ref(ref):
        return None
    process = None
    if thumb:
        process = (
            f"image/resize,m_lfit,w_{settings.image_thumb_width},h_{settings.image_thumb_height}"
            f"/quality,q_{settings.image_thumb_quality}/format,jpg"
        )
    try:
        return _oss_asset_url(ref, process=process)
    except Exception:
        logger.exception("生成 OSS 预览签名 URL 失败: %s", ref)
        return None


def _init_allowed_file_dirs() -> None:
    """初始化允许访问的目录列表（在应用启动后调用以确保路径已解析）"""
    global _ALLOWED_FILE_DIRS
    _ALLOWED_FILE_DIRS = [
        settings.assets_dir.resolve(),
        settings.fonts_dir.resolve(),
        settings.templates_dir.resolve(),
        settings.thumbs_dir.resolve(),
        settings.downloads_dir.resolve(),
        settings.resources_dir.resolve(),
    ]


def _safe_abs(stored_path: str | None) -> Path | None:
    """将数据库中的相对/绝对路径转为 Path，并验证在允许的目录范围内。"""
    path = settings.abs_path(stored_path)
    if path is None:
        return None
    try:
        resolved = path.resolve()
    except (OSError, RuntimeError):
        return None
    # 检查路径是否在允许的目录范围内
    for allowed_dir in _ALLOWED_FILE_DIRS:
        try:
            resolved.relative_to(allowed_dir)
            return resolved
        except ValueError:
            continue
    logger.warning(
        "_safe_abs 拒绝访问允许目录之外的路径: stored=%s resolved=%s",
        stored_path,
        resolved,
    )
    return None


def _uploaded_font_abs(stored_path: str | None) -> Path | None:
    path = settings.abs_path(stored_path)
    if path is None:
        return None
    try:
        path.resolve().relative_to(settings.fonts_dir.resolve())
    except ValueError:
        return None
    return path


def _resource_file_abs(stored_path: str | None) -> Path | None:
    if stored_path and is_oss_ref(stored_path):
        try:
            path = oss_storage.materialize(stored_path)
            _MATERIALIZED_REFS[path] = stored_path
            scope = _MATERIALIZED_SCOPE.get()
            if scope is not None:
                scope.add(path)
            return path
        except Exception:
            logger.exception("OSS 对象下载失败: %s", stored_path)
            return None
    path = settings.abs_path(stored_path)
    if path is None:
        return None
    try:
        path.resolve().relative_to(settings.assets_dir.resolve())
    except ValueError:
        return None
    return path


def cleanup_materialized(paths: list[Path | None]) -> None:
    """Remove only temporary files downloaded by ``_resource_file_abs``."""
    for path in paths:
        if path is None:
            continue
        ref = _MATERIALIZED_REFS.pop(path, None)
        if ref is not None:
            path.unlink(missing_ok=True)


def materialized_paths() -> tuple[Path, ...]:
    """Return currently materialized OSS files for request/task cleanup."""
    return tuple(_MATERIALIZED_REFS)


@contextmanager
def materialization_scope():
    """Track and clean OSS downloads belonging to one request/task."""
    owned: set[Path] = set()
    token = _MATERIALIZED_SCOPE.set(owned)
    try:
        yield owned
    finally:
        _MATERIALIZED_SCOPE.reset(token)
        cleanup_materialized(list(owned))


def _delete_resource_files(paths: list[Path | str | None], version_ids: list[int]) -> None:
    parents: set[Path] = set()
    for path in paths:
        if path is None:
            continue
        if isinstance(path, str) and is_oss_ref(path):
            try:
                oss_storage.delete(path)
            except Exception:
                logger.exception("删除 OSS 资源失败，等待对象存储生命周期策略清理: %s", path)
            continue
        if isinstance(path, str):
            local_path = settings.abs_path(path)
            if local_path is not None:
                path = local_path
        object_ref = _MATERIALIZED_REFS.pop(path, None) if isinstance(path, Path) else None
        if object_ref:
            try:
                oss_storage.delete(object_ref)
            except Exception:
                logger.exception("删除 OSS 资源失败，等待对象存储生命周期策略清理: %s", object_ref)
        if isinstance(path, Path):
            parents.add(path.parent)
        if isinstance(path, Path):
            path.unlink(missing_ok=True)
    thumbs_dir = settings.thumbs_dir
    for version_id in version_ids:
        for thumb in thumbs_dir.glob(f"preview_v{version_id}_*.jpg"):
            thumb.unlink(missing_ok=True)
    resources_dir = settings.resources_dir.resolve()
    for parent in sorted(parents, key=lambda item: len(item.parts), reverse=True):
        current = parent
        while True:
            try:
                current.resolve().relative_to(resources_dir)
            except ValueError:
                break
            if current == resources_dir:
                break
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent


def _delete_template_files(paths: list[Path | str | None]) -> None:
    parents: set[Path] = set()
    for path in paths:
        if path is None:
            continue
        if isinstance(path, str) and is_oss_ref(path):
            try:
                oss_storage.delete(path)
            except Exception:
                logger.exception("删除 OSS 模板失败，等待对象存储生命周期策略清理: %s", path)
            continue
        if isinstance(path, str):
            local_path = settings.abs_path(path)
            if local_path is not None:
                path = local_path
        object_ref = _MATERIALIZED_REFS.pop(path, None) if isinstance(path, Path) else None
        if object_ref:
            try:
                oss_storage.delete(object_ref)
            except Exception:
                logger.exception("删除 OSS 模板失败，等待对象存储生命周期策略清理: %s", object_ref)
        if isinstance(path, Path):
            parents.add(path.parent)
        if isinstance(path, Path):
            path.unlink(missing_ok=True)
    templates_dir = settings.templates_dir.resolve()
    for parent in sorted(parents, key=lambda item: len(item.parts), reverse=True):
        current = parent
        while True:
            try:
                current.resolve().relative_to(templates_dir)
            except ValueError:
                break
            if current.resolve() == templates_dir:
                break
            try:
                current.rmdir()
            except OSError:
                break
            current = current.parent


def _content_disposition(filename: str) -> str:
    quoted = quote(filename)
    return f"attachment; filename*=UTF-8''{quoted}"


def _preview_thumb_path(source_path: Path, version_id: int) -> Path:
    thumbs_dir = settings.thumbs_dir
    thumbs_dir.mkdir(parents=True, exist_ok=True)
    mtime = source_path.stat().st_mtime_ns
    return thumbs_dir / f"preview_v{version_id}_{mtime}_{settings.image_thumb_width}x{settings.image_thumb_height}_q{settings.image_thumb_quality}.jpg"


def _preview_thumb_bytes(source_path: Path) -> bytes:
    """Render a transient JPEG thumbnail without persisting a second asset."""
    thumb_w = settings.image_thumb_width
    thumb_h = settings.image_thumb_height
    with Image.open(source_path) as image:
        image.thumbnail((thumb_w, thumb_h), Image.Resampling.LANCZOS)
        canvas = Image.new("RGB", (thumb_w, thumb_h), (248, 250, 252))
        if image.mode != "RGBA":
            image = image.convert("RGBA")
        left = (thumb_w - image.width) // 2
        top = (thumb_h - image.height) // 2
        canvas.paste(image, (left, top), image)
        buffer = io.BytesIO()
        canvas.save(buffer, format="JPEG", quality=settings.image_thumb_quality, optimize=True, progressive=True)
        return buffer.getvalue()


def _ensure_preview_thumb(source_path: Path, version_id: int) -> Path:
    target = _preview_thumb_path(source_path, version_id)
    if target.exists():
        return target
    # Write to a sibling temporary file and publish it atomically.  A failed
    # PIL encode (or a worker interruption) must never leave a truncated JPEG
    # at the cache path that subsequent requests would mistake for a valid
    # thumbnail.
    temp_target = target.with_name(f".{target.name}.{uuid.uuid4().hex}.tmp")
    try:
        temp_target.write_bytes(_preview_thumb_bytes(source_path))
        os.replace(temp_target, target)
        return target
    finally:
        temp_target.unlink(missing_ok=True)


def _validate_ppt_upload(upload: UploadFile) -> None:
    suffix = Path(upload.filename or "").suffix.lower()
    if suffix not in PPT_EXTENSIONS:
        raise HTTPException(400, "目前仅支持上传 PPTX 文件")
